project:
  type: website

website:
  title: "sql4stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: SQL_Scrolly.qmd
        text: background
      - href: joins.qmd
        text: joins
      - href: parquet.qmd
        text: parquet files
      - href: crosstab_pivot_comp.qmd
        text: SQL Pivoting

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



