project:
  type: website

website:
  title: "sql4stats"
  navbar:
    href: index.qmd
    left:
      - text: "Informational Resources"
        menu:
          - href: SQL_Scrolly_reformatted.qmd
            text: SQL:Indexing and B-Trees
          - href: joins.qmd
            text: Joins
          - href: parquet.qmd
            text: File Formats and DuckDB
      - text: "Theory in Practice"
        menu:
          - href: native_v_direct.qmd
            text: Native DuckDB vs. Direct Querying
          - href: row_v_file.qmd
            text: Parquet Querying Time Exploration
          - href: join_optimization.qmd
            text: Join Algorithms and Order
      - text: "Tutorials"
        menu: 
          - href: sql_upload_guide.qmd
            text: SQL Upload Guide
          - href: crosstab_pivot_comp.qmd
            text: Pivot Types
          
      - text: "About"
        href: about.qmd
      - text: "References"
        href: references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - global_style.scss
    toc: true



