<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Join Algorithms and Join Order in PostgreSQL – sql4stats</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-3b131c22a8ecff6f91e3cb37a2824cbb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f7104779465153de3e46fc4686730ebe.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">sql4stats</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-informational-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Informational Resources</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-informational-resources">    
        <li>
    <a class="dropdown-item" href="./SQL_Scrolly_reformatted.html">
 <span class="dropdown-text">SQL:Indexing and B-Trees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./joins.html">
 <span class="dropdown-text">Joins</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./parquet.html">
 <span class="dropdown-text">File Formats and DuckDB</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-theory-in-practice" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Theory in Practice</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-theory-in-practice">    
        <li>
    <a class="dropdown-item" href="./native_v_direct.html">
 <span class="dropdown-text">Native DuckDB vs.&nbsp;Direct Querying</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./row_v_file.html">
 <span class="dropdown-text">Parquet Querying Time Exploration</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./join_optimization.html">
 <span class="dropdown-text">Join Algorithms and Order</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tutorials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tutorials</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tutorials">    
        <li>
    <a class="dropdown-item" href="./sql_upload_guide.html">
 <span class="dropdown-text">SQL Upload Guide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./crosstab_pivot_comp.html">
 <span class="dropdown-text">Pivot Types</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./references.html"> 
<span class="menu-text">References</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
  <li><a href="#indexing-the-tables" id="toc-indexing-the-tables" class="nav-link" data-scroll-target="#indexing-the-tables">Indexing the Tables</a></li>
  <li><a href="#simulation-settings" id="toc-simulation-settings" class="nav-link" data-scroll-target="#simulation-settings">Simulation Settings</a></li>
  <li><a href="#query-syntax-good-vs.-bad-order" id="toc-query-syntax-good-vs.-bad-order" class="nav-link" data-scroll-target="#query-syntax-good-vs.-bad-order">Query Syntax: Good vs.&nbsp;Bad Order</a></li>
  </ul></li>
  <li><a href="#running-the-simulation" id="toc-running-the-simulation" class="nav-link" data-scroll-target="#running-the-simulation">Running the Simulation</a>
  <ul class="collapse">
  <li><a href="#run_repeated" id="toc-run_repeated" class="nav-link" data-scroll-target="#run_repeated">RUN_REPEATED</a></li>
  <li><a href="#running-all-six-combinations" id="toc-running-all-six-combinations" class="nav-link" data-scroll-target="#running-all-six-combinations">Running all six combinations</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#reading-query-plans" id="toc-reading-query-plans" class="nav-link" data-scroll-target="#reading-query-plans">Reading Query Plans</a></li>
  </ul></li>
  <li><a href="#a-note-on-cold-cache" id="toc-a-note-on-cold-cache" class="nav-link" data-scroll-target="#a-note-on-cold-cache">A note on cold cache</a></li>
  <li><a href="#why-the-planner-makes-these-choices-estimated-vs.-actual-rows" id="toc-why-the-planner-makes-these-choices-estimated-vs.-actual-rows" class="nav-link" data-scroll-target="#why-the-planner-makes-these-choices-estimated-vs.-actual-rows">Why the planner makes these choices: estimated vs.&nbsp;actual rows</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#practical-takeaways" id="toc-practical-takeaways" class="nav-link" data-scroll-target="#practical-takeaways">Practical Takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Join Algorithms and Join Order in PostgreSQL</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>When you write a multi-table <code>JOIN</code>, you specify which tables connect and on what columns — but you do not specify how the database should physically combine them, nor in what order. Normally, the query optimizer uses the distribution of data within the tables to estimate the size of intermediate results and create a query plan.</p>
<p>This simulation isolates and measures the impacts of two main optimization decisions:</p>
<ul>
<li><strong>Join strategy</strong> — the physical algorithm used to match rows between two tables. PostgreSQL has three: <strong>Nested Loop</strong>, <strong>Hash Join</strong>, and <strong>Merge Join</strong>. For more information on these strategies, see the <a href="./joins.html">Joins page</a>.</li>
<li><strong>Join order</strong> — the sequence in which tables are brought into the join. Starting from heavily-filtered small tables keeps intermediate results tiny; starting from large unfiltered tables forces the engine to carry millions of rows through every step.</li>
</ul>
<p>Normally the planner picks both automatically using table statistics and cost estimates.To <em>see</em> the effect of each choice, we override the planner with session-level <code>SET</code> commands, force one strategy and one order at a time, and time the result. This is mostly a teaching device — in production you almost always let the planner decide.</p>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>For this simulation, we’ll be using a modified version of PostgreSQL 13.1 which <a href="./references.html"><span class="citation" data-cites="Han2021">Han et al. (2021)</span></a> used in their paper on cardinality estimation methods. Use the instructions from their <a href="https://github.com/Nathaniel-Han/End-to-End-CardEst-Benchmark/tree/master">GitHub repository</a> to set up PostgreSQL on your own computer.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RPostgres)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  RPostgres<span class="sc">::</span><span class="fu">Postgres</span>(),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dbname =</span> <span class="st">"stats"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">host   =</span> <span class="st">"127.0.0.1"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">port   =</span> <span class="dv">5432</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">user   =</span> <span class="fu">Sys.info</span>()[[<span class="st">"user"</span>]]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>First, we connect to the database. A local PostgreSQL server connection is ideal for this simulation as it will have the least performance variability.</p>
<p>We’ll be using STATS-CEB, an anonymized dump of user-contributed content from the <a href="https://stats.stackexchange.com/"> Stats StackExchange Network </a>, a discussion board featuring questions about various topics in statistics. This database contains 8 tables: tags, comments, badges, posts, users, postLinks, postHistory, and votes. These tables are connected, all by primary keys such as post ID and user ID. For this simulation, a simplified version provided by <a href="./references.html"><span class="citation" data-cites="Han2021">Han et al. (2021)</span></a> and included in the paper’s <a href="https://github.com/Nathaniel-Han/End-to-End-CardEst-Benchmark/tree/master">GitHub repository</a> acts as a helpful benchmark for query performance assessment. Follow the instructions in the README for downloading PostgreSQL and the dataset.</p>
<p>For a more in-depth tutorial on setting up a SQL connection in R, see the <a href="./sql_upload_guide.html">Data Upload Tutorial</a>.</p>
<section id="indexing-the-tables" class="level3">
<h3 class="anchored" data-anchor-id="indexing-the-tables">Indexing the Tables</h3>
<p>First, we need to create indexes on the columns involved in the joins we’re performing. This ensures that the nested loop algorithm will be as efficient as possible. For more information on how indexes are structured in SQL, see the <a href="./SQL_Scrolly_reformatted.html#sec-ch3"> indexes and b-trees page </a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"CREATE INDEX IF NOT EXISTS idx_votes_postid       ON votes(postid)"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"CREATE INDEX IF NOT EXISTS idx_posts_owneruserid  ON posts(owneruserid)"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"CREATE INDEX IF NOT EXISTS idx_badges_userid      ON badges(userid)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="simulation-settings" class="level3">
<h3 class="anchored" data-anchor-id="simulation-settings">Simulation Settings</h3>
<p>In PostgreSQL, session variables can be specifically controlled to simulate different optimizer decisions.</p>
<ul>
<li><code>enable_nestloop</code>, <code>enable_hashjoin</code>, <code>enable_mergejoin</code> — turn each physical algorithm on or off. By enabling exactly one at a time, we force the planner to use that strategy.</li>
<li><code>join_collapse_limit</code> / <code>from_collapse_limit</code> — when set to <code>1</code>, the planner is forbidden from reordering the tables and must join them in the literal order written in the <code>FROM</code> clause. This is what lets us dictate join <em>order</em>.</li>
<li><code>max_parallel_workers_per_gather</code> — set to <code>0</code> to turn off parallelism, so timing differences reflect the algorithm and not the number of workers.</li>
</ul>
<p>A key idea: because <code>join_collapse_limit = 1</code> makes the engine respect the written order, the <em>same logical query</em> written with its tables in a different sequence becomes a different physical plan.</p>
</section>
<section id="query-syntax-good-vs.-bad-order" class="level3">
<h3 class="anchored" data-anchor-id="query-syntax-good-vs.-bad-order">Query Syntax: Good vs.&nbsp;Bad Order</h3>
<p>Both queries below answer the <strong>exact same question</strong> — count the rows produced by joining votes to their posts, those posts to their owners, and those owners to their badges, keeping only upvotes (<code>votetypeid = 2</code>) on well-scored posts (<code>score &gt; 10</code>) owned by high-reputation users (<code>reputation &gt; 1000</code>). They return identical results. The only difference is the order the tables are listed in.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sql_good_order <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM votes v</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN posts  p ON v.postid = p.id</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN users  u ON p.owneruserid = u.id</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN badges b ON b.userid = u.id</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE v.votetypeid = 2</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="st">    AND p.score &gt; 10</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="st">    AND u.reputation &gt; 1000</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Bad order: large/unfiltered tables first</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>sql_bad_order <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="st">  SELECT COUNT(*)</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="st">  FROM badges b</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN users  u ON b.userid = u.id</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN posts  p ON p.owneruserid = u.id</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="st">  JOIN votes  v ON v.postid = p.id</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="st">  WHERE v.votetypeid = 2</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="st">    AND p.score &gt; 10</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="st">    AND u.reputation &gt; 1000</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<ul>
<li><strong>Good order</strong> leads with <code>votes</code> and <code>posts</code>, where the <code>WHERE</code> filters are most selective, so the very first join already works on a much smaller set of rows.</li>
<li><strong>Bad order</strong> leads with <code>badges</code> and <code>users</code>, the large tables which are never filtered, so early intermediate results stay huge.</li>
</ul>
<p>To verify this result, we can run both of the queries separately.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, sql_good_order)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    count
1 5854758</code></pre>
</div>
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(con, sql_bad_order)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    count
1 5854758</code></pre>
</div>
</div>
</section>
</section>
<section id="running-the-simulation" class="level2">
<h2 class="anchored" data-anchor-id="running-the-simulation">Running the Simulation</h2>
<section id="run_repeated" class="level3">
<h3 class="anchored" data-anchor-id="run_repeated">RUN_REPEATED</h3>
<p>To get a stable measurement we run one throwaway query first. This loads the relevant data pages into PostgreSQL’s buffer cache (a <strong>warm-cache</strong> measurement). Then, we run the query <code>n</code> more times, scraping the <code>Execution Time</code> and <code>Planning Time</code> lines out of each query plan.</p>
<p><code>EXPLAIN ANALYZE</code> is the tool doing the real work here: it actually executes the query and reports how long each step took, as opposed to plain <code>EXPLAIN</code>, which only prints the query plan.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>run_repeated_warm <span class="ot">&lt;-</span> <span class="cf">function</span>(con, query, <span class="at">n =</span> <span class="dv">10</span>) {</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Warm-up run: loads pages into cache, result discarded</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dbGetQuery</span>(con, <span class="fu">paste</span>(<span class="st">"EXPLAIN ANALYZE"</span>, query))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Timed trials</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="cf">function</span>(i) {</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    lines <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="fu">paste</span>(<span class="st">"EXPLAIN ANALYZE"</span>, query))[[<span class="dv">1</span>]]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    exec_time <span class="ot">&lt;-</span> lines[<span class="fu">grep</span>(<span class="st">"Execution Time"</span>, lines)] <span class="sc">|&gt;</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    plan_time <span class="ot">&lt;-</span> lines[<span class="fu">grep</span>(<span class="st">"Planning Time"</span>, lines)] <span class="sc">|&gt;</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">run =</span> i, <span class="at">exec_ms =</span> exec_time, <span class="at">plan_ms =</span> plan_time)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">|&gt;</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list_rbind</span>()</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="running-all-six-combinations" class="level3">
<h3 class="anchored" data-anchor-id="running-all-six-combinations">Running all six combinations</h3>
<p>We now cross the two join orders with the three join strategies, forcing one strategy at a time by toggling the <code>enable_*</code> flags. That gives six timing distributions of ten runs each.</p>
<section id="nested-loop" class="level4">
<h4 class="anchored" data-anchor-id="nested-loop">Nested Loop</h4>
<p>First, we enable the nested loop and disable hash and merge join algorithms.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_nestloop  = on"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_hashjoin  = off"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_mergejoin = off"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>We’ll run the query once to warm the cache, then extract the results of the next 10 repetitions.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>results_nest_good <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_good_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Nested Loop"</span>, <span class="at">order =</span> <span class="st">"good"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>results_nest_bad  <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_bad_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Nested Loop"</span>, <span class="at">order =</span> <span class="st">"bad"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Now, we’ll go through the same process for hash join.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_nestloop  = off"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_hashjoin  = on"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_mergejoin = off"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>results_hash_good <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_good_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Hash Join"</span>, <span class="at">order =</span> <span class="st">"good"</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>results_hash_bad  <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_bad_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Hash Join"</span>, <span class="at">order =</span> <span class="st">"bad"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Same for merge join:</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_nestloop  = off"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_hashjoin  = off"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_mergejoin = on"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>results_merge_good <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_good_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Merge Join"</span>, <span class="at">order =</span> <span class="st">"good"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>results_merge_bad  <span class="ot">&lt;-</span> <span class="fu">run_repeated_warm</span>(con, sql_bad_order, <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">join_type =</span> <span class="st">"Merge Join"</span>, <span class="at">order =</span> <span class="st">"bad"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"DISCARD ALL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>Here’s a plot comparing execution times between different join orders and algorithms.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  results_nest_good, results_nest_bad,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  results_hash_good, results_hash_bad,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  results_merge_good, results_merge_bad</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> join_type, <span class="at">y =</span> exec_ms, <span class="at">color =</span> order)) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Effect of join strategy on execution time"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"4-table join: votes, posts, users, badges"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Join Strategy"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"Execution time (ms)"</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="join_optimization_files/figure-html/warm-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Warm-cache execution time across the six strategy × order combinations.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>What the plot shows.</strong> Each strategy responds differently to a bad join order. A <strong>Nested Loop</strong> is the most order-sensitive: for every row from the outer side it probes the inner side, so if the outer side starts large (bad order) the probe count explodes. A <strong>Hash Join</strong> builds a hash table on one input and streams the other past it, which makes it far more forgiving of a bad starting order. A <strong>Merge Join</strong> requires both inputs sorted on the join key, so its cost is dominated by sorting and it sits somewhere in between. In short: a good join order helps every strategy, but it <em>rescues</em> the Nested Loop.</p>
</section>
<section id="reading-query-plans" class="level3">
<h3 class="anchored" data-anchor-id="reading-query-plans">Reading Query Plans</h3>
<p>To understand why some queries take longer than others, it can be helpful to read the plans created by the query optimizer. Wrapping a query in <code>EXPLAIN ANALYZE</code> allows us to read the query plan and see exactly how long each step of the query takes.</p>
<p>Before unpacking the query plans themselves, it’s important to recognize that they are most easily read from bottom to top. Each node/line pulls on the results from the child nodes indented below it. In other words, even though it initializes the query plan, the step labeled “1” in the plan actually finishes last. Additionally, the last 3 lines are summary statistics describing the number of heap fetches (when an Index Only Scan has to go back to the table because the index alone is insufficient), the planning time, and the execution time of the query.</p>
<p>Before unpacking the query plans themselves, it’s important to recognize that they are structured as trees and most easily read from bottom to top. Each node pulls rows from the child nodes indented beneath it, so the leaf nodes produce the first rows and the topmost node — labeled “1” — is the last to finish, even though it’s the first one called. (A few node types, like <code>Hash</code> and <code>Sort</code>, are exceptions in that they must consume their entire input before passing anything up, but the overall direction of reading still holds.) Finally, the last two lines report the planning time and execution time for the whole query, and any <code>Heap Fetches</code> line belongs to an Index Only Scan directly above it — it counts the times that scan had to return to the table because the index alone couldn’t confirm a row’s visibility.</p>
<section id="auto-optimized-join" class="level4">
<h4 class="anchored" data-anchor-id="auto-optimized-join">Auto-Optimized Join</h4>
<p>First, we’ll run the query and allow the engine to optimize freely.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>auto_plan <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="fu">paste</span>(<span class="st">"EXPLAIN ANALYZE"</span>, sql_bad_order))[[<span class="dv">1</span>]]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>auto_exec <span class="ot">&lt;-</span> auto_plan <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"Execution Time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>auto_plan_time <span class="ot">&lt;-</span> auto_plan <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"Planning Time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>auto_plan  <span class="co"># print the plan for the reader</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Aggregate  (cost=2904.66..2904.67 rows=1 width=8) (actual time=1330.417..1330.418 rows=1 loops=1)"                                                
 [2] "  -&gt;  Nested Loop  (cost=805.26..2898.52 rows=2457 width=0) (actual time=12.625..1084.898 rows=5854758 loops=1)"                                  
 [3] "        Join Filter: (u.id = b.userid)"                                                                                                           
 [4] "        -&gt;  Nested Loop  (cost=804.97..2858.88 rows=71 width=8) (actual time=12.605..64.835 rows=45869 loops=1)"                                  
 [5] "              -&gt;  Hash Join  (cost=804.55..2773.90 rows=25 width=12) (actual time=12.548..23.868 rows=2287 loops=1)"                              
 [6] "                    Hash Cond: (p.owneruserid = u.id)"                                                                                            
 [7] "                    -&gt;  Seq Scan on posts p  (cost=0.00..1959.70 rows=3676 width=8) (actual time=0.016..10.144 rows=3552 loops=1)"                
 [8] "                          Filter: (score &gt; 10)"                                                                                                   
 [9] "                          Rows Removed by Filter: 88424"                                                                                          
[10] "                    -&gt;  Hash  (cost=801.06..801.06 rows=279 width=4) (actual time=12.518..12.519 rows=305 loops=1)"                               
[11] "                          Buckets: 1024  Batches: 1  Memory Usage: 19kB"                                                                          
[12] "                          -&gt;  Seq Scan on users u  (cost=0.00..801.06 rows=279 width=4) (actual time=0.008..12.375 rows=305 loops=1)"             
[13] "                                Filter: (reputation &gt; 1000)"                                                                                      
[14] "                                Rows Removed by Filter: 40020"                                                                                    
[15] "              -&gt;  Index Scan using idx_votes_postid on votes v  (cost=0.42..3.34 rows=6 width=4) (actual time=0.003..0.016 rows=20 loops=2287)"   
[16] "                    Index Cond: (postid = p.id)"                                                                                                  
[17] "                    Filter: (votetypeid = 2)"                                                                                                     
[18] "                    Rows Removed by Filter: 3"                                                                                                    
[19] "        -&gt;  Index Only Scan using idx_badges_userid on badges b  (cost=0.29..0.51 rows=4 width=4) (actual time=0.002..0.013 rows=128 loops=45869)"
[20] "              Index Cond: (userid = p.owneruserid)"                                                                                               
[21] "              Heap Fetches: 0"                                                                                                                    
[22] "Planning Time: 2.041 ms"                                                                                                                          
[23] "Execution Time: 1330.503 ms"                                                                                                                      </code></pre>
</div>
</div>
<p>Following the rows from the bottom up: PostgreSQL begins with two filtered scans. It scans <code>posts</code> and keeps only the 3,552 rows with <code>score &gt; 10</code> (line 7, discarding 88,424), and scans <code>users</code> to keep the 305 with <code>reputation &gt; 1000</code> (line 12), building a hash table on those users (line 10). Those two filtered inputs meet at the <code>hash join</code> (line 5), which matches <code>posts</code> to their <code>owners</code> on <code>owneruserid</code> and emits 2,287 rows. From there the rows flow upward through two <code>nested loops</code>: the first probes <code>votes</code> by index once per post (line 15), growing the result to 45,869 rows, and the second probes <code>badges</code> by index once per user (line 19), ballooning it to 5,854,758. Those rows finally arrive at the <code>Aggregate</code> (line 1), which collapses them into a single count.</p>
<p>Notice that we wrote the bad order in the <code>FROM</code> clause, but with reordering left enabled (<code>join_collapse_limit</code> at its default), the planner ignored our written order entirely. It led with <code>posts</code> and <code>users</code> — the two tables carrying the <code>WHERE</code> filters, and therefore the most selective — and pushed the unfiltered fan-out to the very end. Left to its own devices, the planner reconstructs something close to the good order on its own.</p>
<p>Each node reports <code>actual time=startup..total</code>, where the total is cumulative and measured per loop. Reading these upward shows the cost concentrating in one place: everything through the hash join finishes early, the first nested loop shortly after, and then the top nested loop dominates the runtime. That final node is the whole query. It turns 45,869 input rows into 5,854,758 output rows because each user owns roughly 128 badges (<code>rows=128 loops=45869</code> on line 19), and pushing those 5.85 million rows through the join filter is where the bulk of the 1331 ms runtime lives.</p>
</section>
<section id="manually-defined-inefficient-join" class="level4">
<h4 class="anchored" data-anchor-id="manually-defined-inefficient-join">Manually Defined, Inefficient Join</h4>
<p>For comparison, we’ll run the same query, but this time, we’ll force the engine to run nested loop joins on our defined “bad order” without allowing the optimizer to manipulate it.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET max_parallel_workers_per_gather = 0"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET join_collapse_limit = 1"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET from_collapse_limit = 1"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_nestloop  = on"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_hashjoin  = off"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET enable_mergejoin = off"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>forced_plan <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="fu">paste</span>(<span class="st">"EXPLAIN ANALYZE"</span>, sql_bad_order))[[<span class="dv">1</span>]]</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>forced_exec <span class="ot">&lt;-</span> forced_plan <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"Execution Time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>forced_plan_time <span class="ot">&lt;-</span> forced_plan <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"Planning Time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_extract</span>(<span class="st">"[0-9.]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>forced_plan  <span class="co"># print the plan for the reader</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Aggregate  (cost=4672.77..4672.78 rows=1 width=8) (actual time=5137.780..5137.781 rows=1 loops=1)"                                                         
 [2] "  -&gt;  Nested Loop  (cost=1.01..4666.63 rows=2457 width=0) (actual time=0.034..4854.670 rows=5854758 loops=1)"                                              
 [3] "        -&gt;  Nested Loop  (cost=0.58..1719.61 rows=867 width=4) (actual time=0.026..1215.462 rows=292650 loops=1)"                                          
 [4] "              -&gt;  Nested Loop  (cost=0.29..1449.36 rows=552 width=8) (actual time=0.019..6.775 rows=12371 loops=1)"                                        
 [5] "                    -&gt;  Seq Scan on users u  (cost=0.00..801.06 rows=279 width=4) (actual time=0.007..3.684 rows=305 loops=1)"                             
 [6] "                          Filter: (reputation &gt; 1000)"                                                                                                     
 [7] "                          Rows Removed by Filter: 40020"                                                                                                   
 [8] "                    -&gt;  Index Only Scan using idx_badges_userid on badges b  (cost=0.29..2.28 rows=4 width=4) (actual time=0.003..0.007 rows=41 loops=305)"
 [9] "                          Index Cond: (userid = u.id)"                                                                                                     
[10] "                          Heap Fetches: 0"                                                                                                                 
[11] "              -&gt;  Index Scan using idx_posts_owneruserid on posts p  (cost=0.29..0.48 rows=1 width=8) (actual time=0.009..0.096 rows=24 loops=12371)"      
[12] "                    Index Cond: (owneruserid = b.userid)"                                                                                                  
[13] "                    Filter: (score &gt; 10)"                                                                                                                  
[14] "                    Rows Removed by Filter: 246"                                                                                                           
[15] "        -&gt;  Index Scan using idx_votes_postid on votes v  (cost=0.42..3.34 rows=6 width=4) (actual time=0.003..0.011 rows=20 loops=292650)"                
[16] "              Index Cond: (postid = p.id)"                                                                                                                 
[17] "              Filter: (votetypeid = 2)"                                                                                                                    
[18] "              Rows Removed by Filter: 2"                                                                                                                   
[19] "Planning Time: 0.211 ms"                                                                                                                                   
[20] "Execution Time: 5137.824 ms"                                                                                                                               </code></pre>
</div>
</div>
<p>Following the rows from the bottom up: with reordering forbidden (<code>join_collapse_limit = 1</code>), the engine must honor the literal <code>FROM</code> order, so it starts where we told it to — the unfiltered tables. It scans <code>users</code>, keeping the 305 rows with <code>reputation &gt; 1000</code> (line 5), and for each one probes <code>badges</code> by index (line 8), producing 12,371 rows. That result drives a nested loop into <code>posts</code> (line 11), probed once per badge — 12,371 loops — which grows the result to 292,650 rows. Those in turn drive a nested loop into <code>votes</code> (line 15), probed 292,650 times, fanning out to 5,854,758 rows before the <code>Aggregate</code> (line 1) collapses them to a single count. Every join is a nested loop, and no hash table appears anywhere.</p>
<p>Compare the intermediate row counts to the free plan. There, the engine led with the two filtered tables and kept early results tiny — the first join carried 2,287 rows, the next 45,869. Here, forbidden from leading with the selective filters, the engine carries 12,371 rows out of the very first join and 292,650 out of the second. The same 5.85 million rows arrive at the top in both plans, but the forced order hauls a far larger intermediate result through the back half of the tree, and pays for it one row at a time: the <code>votes</code> index scan (line 15) executes across 292,650 loops rather than the 2,287 loops of the free plan. The slowdown shows up directly in the totals — execution time rises from roughly 1331 ms to 5138 ms (line 20), a 3.9-fold penalty for a query returning the identical single number.</p>
<p>This is the worst case the earlier boxplots only hinted at — a bad order and the most order-sensitive algorithm, combined, on a query the planner would otherwise have rescued. The top join still emits the same 5.85 million rows it always did, and the planner still expected only 2,457; what changed is that we stripped away its two best safeguards — the freedom to lead with the selective tables, and the option to use a hash join where a nested loop explodes. Left alone, it used both. Forced, it can use neither.</p>
</section>
</section>
</section>
<section id="a-note-on-cold-cache" class="level2">
<h2 class="anchored" data-anchor-id="a-note-on-cold-cache">A note on cold cache</h2>
<p>Every measurement above is <strong>warm-cache</strong>: the warm-up run loads the relevant pages into PostgreSQL’s buffer pool, so the timed runs reflect the cost of the join algorithm rather than the cost of fetching data from disk. This is the right thing to measure for a query that runs often enough to keep its pages resident in memory.</p>
<p>A <strong>cold-cache</strong> test — closer to a first-of-the-day query, or an analytics query over tables too large to stay in RAM — would be a useful counterpart, but it is genuinely hard to do faithfully here. A real cold measurement has to evict data from two separate layers: PostgreSQL’s own <code>shared_buffers</code>, and the operating system’s page cache underneath it. Neither is reachable from inside a database session. <code>DISCARD ALL</code> only resets session state (planner settings, prepared statements, temp tables) and leaves both caches fully populated; flushing the OS page cache requires root access we don’t have in this environment. Reconnecting on each iteration looks colder but measures essentially the same warm pages.</p>
<p>So rather than report numbers from a harness that can’t actually clear the cache, we’ll state the expectation instead: with a true cold cache the <strong>order penalty should widen, not shrink</strong>. A bad join order carries more rows through each step and therefore touches more pages; when those pages must be read from disk instead of memory, the extra I/O falls hardest on exactly the plan that was already doing the most work — the large-table-first Nested Loop. The warm-cache results below are thus a <em>conservative</em> picture of how much join order matters; on cold data the gap between good and bad order would only grow.</p>
</section>
<section id="why-the-planner-makes-these-choices-estimated-vs.-actual-rows" class="level2">
<h2 class="anchored" data-anchor-id="why-the-planner-makes-these-choices-estimated-vs.-actual-rows">Why the planner makes these choices: estimated vs.&nbsp;actual rows</h2>
<p>The planner doesn’t time queries — it <em>estimates</em> how many rows each step will emit and picks the cheapest plan based on those estimates. When the estimates are wrong, the plan is wrong. The function below pulls every node out of a plan and compares the planner’s <strong>estimated</strong> row count to the <strong>actual</strong> row count, computing a <strong>q-error</strong> defined as <span class="math inline">\(\max\left(\dfrac{\text{estimated}}{\text{actual}}, \dfrac{\text{actual}}{\text{estimated}}\right)\)</span>. A q-error near 1 means the estimate was accurate; a large q-error means the planner was badly misled at that node.</p>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>extract_estimates <span class="ot">&lt;-</span> <span class="cf">function</span>(con, sql, label) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  plan <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(con, <span class="fu">paste</span>(<span class="st">"EXPLAIN ANALYZE"</span>, sql))[[<span class="dv">1</span>]]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Keep only nodes that report actual timing</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  node_lines <span class="ot">&lt;-</span> plan[<span class="fu">grep</span>(<span class="st">"actual time"</span>, plan)]</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(node_lines, <span class="cf">function</span>(line) {</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    operation <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(line,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">"(Nested Loop|Hash Join|Merge Join|Seq Scan|Index Only Scan|Index Scan|Aggregate|Gather)"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    estimated <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(line, <span class="st">"rows=([0-9]+)</span><span class="sc">\\</span><span class="st">s+width"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_extract</span>(<span class="st">"[0-9]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    actual <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(line, <span class="st">"actual time=[0-9.]+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">.[0-9.]+ rows=([0-9]+)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_extract</span>(<span class="st">"[0-9]+$"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    loops <span class="ot">&lt;-</span> <span class="fu">str_extract</span>(line, <span class="st">"loops=([0-9]+)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_extract</span>(<span class="st">"[0-9]+"</span>) <span class="sc">|&gt;</span> <span class="fu">as.numeric</span>()</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">label        =</span> label,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">operation    =</span> operation,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">estimated    =</span> estimated,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">actual       =</span> actual,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">loops        =</span> loops,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">actual_total =</span> actual <span class="sc">*</span> loops,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">q_error =</span> <span class="fu">max</span>(estimated<span class="sc">/</span>actual_total, actual_total<span class="sc">/</span>estimated)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>  }) <span class="sc">|&gt;</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list_rbind</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(operation), <span class="sc">!</span><span class="fu">is.na</span>(estimated), <span class="sc">!</span><span class="fu">is.na</span>(actual))</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET max_parallel_workers_per_gather = 0"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Forced orders: planner not allowed to reorder</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET join_collapse_limit = 1"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>good_estimates <span class="ot">&lt;-</span> <span class="fu">extract_estimates</span>(con, sql_good_order, <span class="st">"forced good order"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>bad_estimates  <span class="ot">&lt;-</span> <span class="fu">extract_estimates</span>(con, sql_bad_order,  <span class="st">"forced bad order"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Auto-optimized: planner free to choose its own order</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dbExecute</span>(con, <span class="st">"SET join_collapse_limit = 8"</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>auto_estimates <span class="ot">&lt;-</span> <span class="fu">extract_estimates</span>(con, sql_good_order, <span class="st">"auto-optimized"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>all_estimates <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(good_estimates, bad_estimates, auto_estimates)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>all_estimates <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span> <span class="fu">kable</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">label</th>
<th style="text-align: left;">operation</th>
<th style="text-align: right;">estimated</th>
<th style="text-align: right;">actual</th>
<th style="text-align: right;">loops</th>
<th style="text-align: right;">actual_total</th>
<th style="text-align: right;">q_error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Aggregate</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.000000e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">2421</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">2.418322e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">6.460423e+02</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">10416</td>
<td style="text-align: right;">70198</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">70198</td>
<td style="text-align: right;">6.739439e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Seq Scan</td>
<td style="text-align: right;">3676</td>
<td style="text-align: right;">3552</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3552</td>
<td style="text-align: right;">1.034910e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">3552</td>
<td style="text-align: right;">71040</td>
<td style="text-align: right;">1.184000e+04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">70198</td>
<td style="text-align: right;">70198</td>
<td style="text-align: right;">7.019800e+04</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced good order</td>
<td style="text-align: left;">Index Only Scan</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">5871232</td>
<td style="text-align: right;">1.467808e+06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Aggregate</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.000000e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">2457</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">2.382889e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">867</td>
<td style="text-align: right;">292650</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">292650</td>
<td style="text-align: right;">3.375433e+02</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">552</td>
<td style="text-align: right;">12371</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12371</td>
<td style="text-align: right;">2.241123e+01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Seq Scan</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">1.093190e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Index Only Scan</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">12505</td>
<td style="text-align: right;">3.126250e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">12371</td>
<td style="text-align: right;">296904</td>
<td style="text-align: right;">2.969040e+05</td>
</tr>
<tr class="even">
<td style="text-align: left;">forced bad order</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">292650</td>
<td style="text-align: right;">5853000</td>
<td style="text-align: right;">9.755000e+05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Aggregate</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.000000e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">2421</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5854758</td>
<td style="text-align: right;">2.418322e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">6.460423e+02</td>
</tr>
<tr class="even">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Nested Loop</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">2287</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2287</td>
<td style="text-align: right;">9.148000e+01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Seq Scan</td>
<td style="text-align: right;">279</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">1.093190e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">2135</td>
<td style="text-align: right;">2.135000e+03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Index Scan</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">2287</td>
<td style="text-align: right;">45740</td>
<td style="text-align: right;">7.623333e+03</td>
</tr>
<tr class="even">
<td style="text-align: left;">auto-optimized</td>
<td style="text-align: left;">Index Only Scan</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">45869</td>
<td style="text-align: right;">5871232</td>
<td style="text-align: right;">1.467808e+06</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Reading this table. The auto-optimized rows show what the planner does when left alone (join_collapse_limit = 8 lets it reorder up to eight tables freely); the two forced labels show the plans we dictated. The first thing to notice is that the worst single q-error isn’t unique to the bad plan — the badges Index Only Scan misestimates by a factor of ~1.5 million in every plan (estimated 4 rows per user, actual 128), because that error lives in a table’s statistics and travels with it no matter where the table is joined. The leaf-level estimates are simply bad, and all three plans inherit them. What separates the plans is not the size of the individual errors but where they fall and how many rows pass through them. Trace the actual column down each plan. In the auto and good plans, the early joins stay small — the hash join emits 2,287 rows, the next nested loop 45,869 — and the catastrophic fan-out to 5.85 million only happens at the final node. In the forced bad order, the row count is already inflated much earlier: the first nested loop emits 12,371 rows, the second 292,650, and the underestimated index scans beneath them (q-errors of ~3e5 and ~9.7e5) are therefore executed across hundreds of thousands of loops rather than a few thousand. The same per-row estimation error costs far more when it sits under a node looping 292,650 times than one looping 2,287 times. This is the mechanism behind the timing differences. A bad order isn’t slow by definition — it’s slow because it forces the planner’s already-wrong estimates to be paid out over much larger intermediate results. The planner costs each plan believing the top join will emit ~2,450 rows (it emits 5.85 million in all three), but in the bad-order plan that misestimate is compounded by every node beneath it also carrying a bloated row count. With accurate leaf statistics the planner would never have chosen a nested loop at the top at all; the cascading underestimate is what makes the expensive plan look cheap.</p>
<p>It is also important to recognize that PostgreSQL’s cardinality estimation methods are deeply flawed, and can sometimes produce catastrophic results on complex multi-table joins. Analysis of these methods goes beyond the scope of this project, but <span class="citation" data-cites="Han2021">Han et al. (2021)</span> produced a study comparing the performance of existing cardinality estimation methods, including contemporary machine-learning and statistically motivated algorithms. It is a very interesting read and explains the deeper mechanics underlying query performance on real-world benchmark datasets.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Nested Loop</th>
<th>Hash Join</th>
<th>Merge Join</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>How it matches rows</strong></td>
<td>Probe inner table once per outer row</td>
<td>Build hash on one side, stream other</td>
<td>Sort both sides, walk in lockstep</td>
</tr>
<tr class="even">
<td><strong>Needs an index?</strong></td>
<td>Strongly benefits from inner index</td>
<td>No</td>
<td>Benefits from pre-sorted inputs</td>
</tr>
<tr class="odd">
<td><strong>Sensitivity to join order</strong></td>
<td>Very high</td>
<td>Low</td>
<td>Moderate</td>
</tr>
<tr class="even">
<td><strong>Best when</strong></td>
<td>Outer side is small after filtering</td>
<td>Inputs are large and unsorted</td>
<td>Inputs already sorted on the key</td>
</tr>
</tbody>
</table>
</section>
<section id="practical-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="practical-takeaways">Practical Takeaways</h2>
<p>First, <strong>join order matters most for Nested Loops</strong>: leading with your most-filtered tables keeps the outer row count — and therefore the probe count — small. Second, the planner’s choices flow directly from its <strong>row estimates</strong>, so accurate statistics (and thus low q-error) are what let it pick the right strategy and order on its own. Forcing these settings is useful for <em>understanding</em> the engine, but in practice the lesson is to keep statistics fresh and write selective filters, then trust the optimizer.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>